image:
  name: electronuserland/builder:wine-chrome-11.19

before_script:
  - yarn gobal add prebuild

test:
  stage: deploy
  script:
    - yarn --version
    - yarn
    - yarn run release:electron
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/*.*