image:
  name: electronuserland/builder:wine-mono-11.19

test:
  stage: deploy
  script:
    - yarn global add prebuild
    - yarn --version
    - yarn
    - yarn run release:electron
    - rm -rf mac
    - rm -rf linux-unpacked
    - rm -rf win-unpacked
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/*.exe
      # - $CI_PROJECT_DIR/dist/*.AppImage
      # - $CI_PROJECT_DIR/dist/*.snap
      # - $CI_PROJECT_DIR/dist/*-mac.tar.gz