image:
  name: electronuserland/builder:wine-mono-11.19

test:
  stage: deploy
  script:
    - yarn global add prebuild
    - yarn --version
    - yarn
    - yarn run release:electron
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist/*.*